### ISSUE TITLE
Compatibility with rpi3 B+

### ISSUE THREAD

**Issue by pyyhttu** [rembertmagri/pi-control-panel-package#1]
I have a Pi-hole in production that is running on Raspberry pi 3 B+, and would like to deploy this control panel package there. However, I see that only rpi4 is supported, so before try and deploy this on my pi-hole, wanted to check if this is compatible with rpi3?

If not, do you have it on roadmap?

**Comment by rembertmagri** [comment]
Hello,

At the moment I don't intend to make the application compatible with RPI3,
simply because I am the only one working on it right now and I don't have a
Pi 3 to test the changes.

That being said, I believe most functions should work out of the box with
rpi3, since the commands are based on that Raspbian SO provides. If you
want to try to install, I'd only recommend not trying to use the dashboard
overclock function and you should be fine.

Another note is I intend to open the source of this project soon, so
hopefully people will get interested in contributing and adding specific
pi3 support.

Regards,
Rembert

**Comment by rembertmagri** [comment]
created issue in the repo containing the source code
